language: ruby

rvm: 
- 2.2

install: gem install jekyll html-proofer

before_script:
 - npm install -g gulp run-sequence gulp-gh-pages

script: gulp test

branches: 
 only: 
  - source

env: 
 global: 
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: "A6Ocbnzo4/V9BTeqcBxGgogybBobNNqkX53cfcMwDUwIOjwILsW4d+J5sFZXRZcIqIuaHKypRcF6e3yDsatXyo61E9s1NuJjM4bd0V9QUf1R/1AVUgtTL+MphtGfL/4lPFffHmMEgmFpyIkjvnyaIjz6agAIoDBT0j6EWQnTIVR/9eWBe98mLCDeggTAqt9PBTxCRyLs5IYx4xr1G0SnibemLC0ftbqgr2mC+85kFGgYmHhToru3rj0zHywOYk29bC5zzWoxIthF4IZCY/Gn9YgRHYV6NPQiS7z0OapLJ9sI3Lv2vhCaWAJwlE8W9yVlj7MqMBuanGAD2MbMdVihvbkXE9X+6OdnEWAzAtAm+ZxRTiKncB+eNM8dfrmhiWcj1rlW/T7HIB+hN7hqJ1ctD/iBG2yRy47VTkeBqctruADjWRfvr4hrDaZCE+88HnbeMXHItuwYxv3rNc36zzJII6kt+D12AEeo7tieV8HTieffYZSwssjJ4K8QoExC0ES06b50zuC+uDSMurAen1OWPaNCz4QrlIaKSJe3EN2bQYoffnVNoBscAd8RtHPsu5TjBsPJWYCRdvAv91od9IX60GuHBsy/cvjYe3ZwqHLcD3AyEYVgWQScgGqSJWMzAcbn9qTKCS+/02DwK44duUDGzSt/pPykdSQ5Y/8x6PB870s="